// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_Date = new DateTime(2023, 10, 25, 15, 56, 21, 643, DateTimeKind.Local).AddTicks(469),
                            Description = "Bu lüks deniz villası, harika bir manzaraya sahiptir ve 8 kişiye kadar konaklama imkanı sunar.",
                            ImageUrl = "https://example.com/villa1.jpg",
                            Name = "Lüks Deniz Villası",
                            Occupancy = 8,
                            Price = 500.0,
                            Sqft = 3000,
                            Updated_Date = new DateTime(2023, 10, 25, 15, 56, 21, 643, DateTimeKind.Local).AddTicks(487)
                        },
                        new
                        {
                            Id = 2,
                            Created_Date = new DateTime(2023, 10, 25, 15, 56, 21, 643, DateTimeKind.Local).AddTicks(491),
                            Description = "Ormanın huzurlu atmosferinde bulunan bu villa, doğa severler için mükemmel bir seçenektir.",
                            ImageUrl = "https://example.com/villa2.jpg",
                            Name = "Orman Kenarı Villa",
                            Occupancy = 6,
                            Price = 400.0,
                            Sqft = 2500,
                            Updated_Date = new DateTime(2023, 10, 25, 15, 56, 21, 643, DateTimeKind.Local).AddTicks(492)
                        },
                        new
                        {
                            Id = 3,
                            Created_Date = new DateTime(2023, 10, 25, 15, 56, 21, 643, DateTimeKind.Local).AddTicks(493),
                            Description = "Şehir merkezinde yer alan bu stüdyo daire, iş seyahati yapanlar için idealdir.",
                            ImageUrl = "https://example.com/villa3.jpg",
                            Name = "Şehir Merkezi Stüdyo Dairesi",
                            Occupancy = 2,
                            Price = 100.0,
                            Sqft = 800,
                            Updated_Date = new DateTime(2023, 10, 25, 15, 56, 21, 643, DateTimeKind.Local).AddTicks(494)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
